"""initial migration

Revision ID: 0740e0ff92b5
Revises: None
Create Date: 2016-03-31 03:17:39.582315

"""

# revision identifiers, used by Alembic.
revision = '0740e0ff92b5'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nick', sa.String(length=10), nullable=True),
    sa.Column('password', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.Column('mobile', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_user_id', sa.Integer(), nullable=True),
    sa.Column('spend_user_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('desc', sa.String(length=30), nullable=True),
    sa.Column('money', sa.Float(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['record_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['spend_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['bill_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bills_record_user_id'), 'bills', ['record_user_id'], unique=False)
    op.create_index(op.f('ix_bills_spend_user_id'), 'bills', ['spend_user_id'], unique=False)
    op.create_index(op.f('ix_bills_type_id'), 'bills', ['type_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bills_type_id'), table_name='bills')
    op.drop_index(op.f('ix_bills_spend_user_id'), table_name='bills')
    op.drop_index(op.f('ix_bills_record_user_id'), table_name='bills')
    op.drop_table('bills')
    op.drop_table('users')
    op.drop_table('bill_types')
    ### end Alembic commands ###
